name: 📄 Documentation issue
description: Kindly use this template if you found any issue in documentation.
title: "Docs: Write a small description here"
labels:
  [
    "status: todo ⏳",
    "📚 docs",
    "hacktoberfest"
  ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a detailed description of the changes you are proposing.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots/videos if applicable
    validations:
      required: false
  - type: dropdown
    id: browser
    attributes:
      label: "🌐 Browser"
      description: "What browser are you using ?"
      options:
        - Google Chrome
        - Brave
        - Microsoft Edge
        - Mozilla Firefox
        - Safari
        - Opera
        - Other
    validations:
      required: true

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist ✅"
      options:
        - label: "I checked and didn't find similar [issue](https://github.com/hack4bengal/s3/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/hack4bengal/s3/blob/main/CONTRIBUTING.md)"
          required: true