  name: 💡 Feature Request
  description: Have a new idea/feature for Hack4Bengal? Please suggest!
  title: "Feature: Write a small description here"
  labels:
    [
      "status: todo ⏳",
      "💡 feature",
      "hacktoberfest"
    ]
  body:
    - type: textarea
      id: description
      attributes:
        label: Description
        description: Write a detailed description of the feature you propose.
      validations:
        required: true
    - type: textarea
      id: solution
      attributes:
        label: Proposed Solution
        description: What needs to be done to implement this feature?
      validations:
        required: true
    - type: textarea
      id: screenshots
      attributes:
        label: Screenshots
        description: Please add screenshots/videos if applicable
      validations:
        required: false
    
    - type: dropdown
      id: browser
      attributes:
        label: "🌐 Browser"
        description: "What browser are you using ?"
        options:
          - Google Chrome
          - Brave
          - Microsoft Edge
          - Mozilla Firefox
          - Safari
          - Opera
          - Other
      validations:
        required: true

    - type: checkboxes
      id: no-duplicate-issues
      attributes:
        label: "Checklist ✅"
        options:
          - label: "I checked and didn't find similar [issue](https://github.com/hack4bengal/s3/issues)"
            required: true

          - label: "I have read the [Contributing Guidelines](https://github.com/hack4bengal/s3/blob/main/CONTRIBUTING.md)"
            required: true